### ISSUE TITLE
CSV-support in `pqrs cat`?

### ISSUE THREAD

**Issue by Hoeze** [manojkarthick/pqrs#15]
Hi, would it be possible to support CSV/TSV in addition to JSON in `pqrs cat`?

**Comment by manojkarthick** [comment]
Hi @Hoeze, thanks for filing this feature request. I've added support for CSV output to the cat subcommand. 

Do note that CSV output is not supported if the parquet file contains struct or byte columns. This is due to a limitation in the CSV writer provided by Apache arrow.

Let me know if you face any issues. Thanks!
