### ISSUE TITLE
Zstd compression level always reported as 1?

### ISSUE THREAD

**Issue by javafanboy** [manojkarthick/pqrs#53]
I created a bunch of Parquet files with Zstd compression and tried different levels, the time taken was different and file size changed but PQRS always reported Zstd(level 1) when I did schema --detailed.

This is on MAC / MacOS / M3.

**Comment by ttencate** [comment]
Heh, I noticed this too last week, and just now spotted your issue. I think I can explain. The compression level that was used to create the file [isn't actually stored](https://parquet.apache.org/docs/file-format/metadata/) in the Parquet file anywhere. Level 1 is reported because the `parquet` library [requires a compression level](https://docs.rs/parquet/52.2.0/parquet/basic/enum.Compression.html) in the enum, and 1 is the default for `ZstdLevel`.

`pqrs` could fix this without any changes needed to the upstream `parquet` library by omitting everything from the first `(` onwards. I'll send a PR.

Edit: actually the printing does come from upstream, [here](https://docs.rs/parquet/52.2.0/src/parquet/schema/printer.rs.html#133). I'll send the PR there :)

**Comment by ttencate** [comment]
It's been fixed upstream. I suppose this issue can be closed, or do you want to wait for a release?

**Comment by javafanboy** [comment]
No that is fine - mostly wanted a confirmation - this "1" sent me on a chase of errors in my code for not setting the desired compression level ...
